version: '3.8'

services:
  # neo4j:
  #   image: neo4j:5.11.0
  #   container_name: graphrag_neo4j
  #   ports:
  #     - "7474:7474" # HTTP
  #     - "7687:7687" # Bolt
  #   environment:
  #     - NEO4J_AUTH=neo4j/password
  #     - NEO4J_PLUGINS=["apoc"]
  #     - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
  #     - NEO4J_dbms_security_procedures_allowlist=apoc.*,gds.*
  #   volumes:
  #     - ./data/neo4j:/data
  #     - ./logs/neo4j:/logs
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:7474"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "7379:7379"
    volumes:
      - ./redis:/data
    command: ["redis-server", "--port", "7379", "--appendonly", "yes"]

  db:
    image: postgres:17
    restart: always
    command: -p 6432 -c log_hostname=off
    ports:
      - 6432:6432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - ./data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - ./:/app
    tty: true
    ports:
      - '8050:8050'
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:6432/app_db
      REDIS_URI: redis://@redis:7379
      PORT: 8050
      BACKEND_SERVER_NAME: 192.168.8.127:8050
      BACKEND_SERVER_URL: http://192.168.8.127:8050
      NODE_ENV: dev
      WORKER: false
      MINIO_BUCKET_NAME: pi
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - minio
    develop:
      watch:
        - action: rebuild
          path: .
          ignore: 
            - node_modules/

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    volumes:
      - ./storage:/data

  in-worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:6432/app_db
      REDIS_URI: redis://@redis:7379
      NODE_ENV: dev
      WORKER: true
      EXTRACTOR_WORKER: false
      MINIO_BUCKET_NAME: pi
    depends_on:
      - db
      - redis
      - minio
    develop:
      watch:
        - action: rebuild
          path: .
          ignore: 
            - node_modules/

  ollama:
    image: ollama/ollama:latest
    volumes:
      -./ollama_data:/root/.ollama
    entrypoint: /bin/sh
    command: 
      - "-c" 
      - |
        ollama serve & 
        sleep 5
        ollama pull llama3.1
        wait

  ex-worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:6432/app_db
      REDIS_URI: redis://@redis:7379
      NODE_ENV: dev
      WORKER: true
      EXTRACTOR_WORKER: true
      MINIO_BUCKET_NAME: pi
    depends_on:
      - db
      - redis
      - minio
    develop:
      watch:
        - action: rebuild
          path: .
          ignore: 
            - node_modules/